### ISSUE TITLE
[FEAT] - HTML Form for mailing list signup

### ISSUE THREAD

**Issue by jdogcoder** [thepurplebubble/site#18]
### What feature would you like to see?

HTML form for mailing list signup > airtable api (data backend) > sendy

### Additional information

Going HTML form route to match branding on site as best as possible.

**Comment by kcoderhtml** [comment]
Netlify forms is just a HTML form that is caught by Netlify

**Comment by jdogcoder** [comment]
LOL

That works then

**Comment by CaenJones** [comment]
I think sendy actually has form-signup templates as well as branding options. I could create one and then use an iframe for the signup page

**Comment by kcoderhtml** [comment]
That would work! My main concern would be people who block iframes as well as how native it would feel.

**Comment by CaenJones** [comment]
I could try to directly embed it…

**Comment by jdogcoder** [comment]
@CaenJones would really love if you could work with @kcoderhtml here, as they have ideas on how this should/will work.

**Comment by kcoderhtml** [comment]
He is designing the form and i'll port everything to astro

**Comment by jdogcoder** [comment]
![CleanShot 2023-12-12 at 20 50 24@2x](https://github.com/thepurplebubble/site/assets/65788728/212d3bb4-dbc1-40a9-b356-da87867ca3bd)

**Comment by jdogcoder** [comment]
For the form, we are doing native HTLM (rly astro) via netlify forms to push to both airtable and sendy

**Comment by jdogcoder** [comment]
```html
<form action="https://postal.hackclub.com/subscribe" method="POST" accept-charset="utf-8">
	<label for="name">Name</label><br/>
	<input type="text" name="name" id="name"/>
	<br/>
	<label for="email">Email</label><br/>
	<input type="email" name="email" id="email"/><br/><br/>
<input type="checkbox" name="gdpr" id="gdpr"/>
<span><strong>Marketing permission</strong>: I give my consent to Purple Bubble to be in touch with me via email using the information I have provided in this form for the purpose of news, updates and marketing.</span>
<br/><br/>
<span><strong>What to expect</strong>: If you wish to withdraw your consent and stop hearing from us, simply click the unsubscribe link at the bottom of every email we send or contact us at team@purplebubble.org. We value and respect your personal data and privacy. To view our privacy policy, please visit our website. By submitting this form, you agree that we may process your information in accordance with these terms.</span>
<br/><br/><div style="display:none;">
	<label for="hp">HP</label><br/>
	<input type="text" name="hp" id="hp"/>
	</div>
	<input type="hidden" name="list" value="xjAecLBfJ3HdnmuBXhvkfg"/>
	<input type="hidden" name="subform" value="yes"/>
	<input type="submit" name="submit" id="submit"/>
</form>
```

**Comment by jdogcoder** [comment]
I am totally cool if we just do this and leave out Airtable, as that just complicates things.

**Comment by kcoderhtml** [comment]
That works for me! Would you want this as a pop up or can i move it to a new page?

**Comment by jdogcoder** [comment]
Fine either way! Sendy handles redirects for subscribed and such, so we should handle those as well!

**Comment by kcoderhtml** [comment]
I created a draft PR, but need some help debugging the function. The response of the function is always nothing, and I can't figure out why.

**Comment by jdogcoder** [comment]
I will see if I can reproduce on my end.

**Comment by jdogcoder** [comment]
@thepurplebubble/website might someone be able to take a look?
