### ISSUE TITLE
[FEAT] - Footer on all pages

### ISSUE THREAD

**Issue by kcoderhtml** [thepurplebubble/site#23]
### What feature would you like to see?

I would like a new component created that will add a footer with "brought to you by netlify" and a link to them as well as "Copywrite © - 2023 Purple Bubble"

**Comment by jdogcoder** [comment]
Are we actually sponsored @kcoderhtml?

**Comment by kcoderhtml** [comment]
Nope! For the opensource plan they want a, quote, "Link to our service on your main page".
![image](https://github.com/thepurplebubble/site/assets/92754843/0a38e587-03f5-4ed9-ba8d-08508382ac0f)

**Comment by jdogcoder** [comment]
Got it. Feel free to go ahead on this.
