### ISSUE TITLE
[FEAT] - SEO, Meta Tags, and OG images 

### ISSUE THREAD

**Issue by jaspermayone** [thepurplebubble/site#4]
### What feature would you like to see?

Improve and optimize SEO, add meta & og image tags

### Additional information

Helpfull tools ~ 

- https://metatags.io
- https://www.seoptimer.com/meta-tag-generator
- https://www.seoptimer.com
- https://ubersuggest.neilpatel.com/open-graph-generator/
- https://freecodetools.org/ogp/
- https://freecodetools.org/twitter-card-generator/
- https://webcode.tools/open-graph-generator
- https://soovle.com
- https://searchresponse.io
- https://www.semrush.com/analytics/keywordmagic/start
- https://www.semrush.com/on-page-seo-checker/
- https://www.seoquake.com/index.html
-

**Comment by CaenJones** [comment]
I can do meta tags and I can add social links at a later date

**Comment by jdogcoder** [comment]
Amazing ty!

**Comment by kcoderhtml** [comment]
@CaenJones are you still willing to do this? We are switching to a new site, but you can add the SEO there if you still want to.
