### ISSUE TITLE
[BUG] - Invalid List ID error after RSVPing.

### ISSUE THREAD

**Issue by DevSrijit** [thepurplebubble/site#52]
### What bug did you encounter?

I got redirected to postal.hackclub.com/subscribe which sent an "Invalid List ID" error after I tried to RSVP.

### What did you expect to happen?

I expected to get to a confirmation page ?

**Comment by kcoderhtml** [comment]
@jaspermayone did you cancel the postal integration?

**Comment by kcoderhtml** [comment]
Thanks for noticing this @DevSrijit!

**Comment by DevSrijit** [comment]
Np !

**Comment by jaspermayone** [comment]
@kcoderhtml I haven't done anything on our side...

**Comment by kcoderhtml** [comment]
Wonderful... so it's an HQ issue then

**Comment by kcoderhtml** [comment]
The decision has been made to migrate to [thepurplebubble/catapult-mailer](https://github.com/thepurplebubble/catapult-mailer) which entails moving the form action into an Astro self submission leading to a fetch request as detailed [here](https://github.com/thepurplebubble/catapult-mailer) and [here for the Astro docs](https://docs.astro.build/en/recipes/build-forms/)

**Comment by EmperorNumerius** [comment]
I will be doing this
