### ISSUE TITLE
[BUG] - The fonts in the form clash with the rest of the website

### ISSUE THREAD

**Issue by kcoderhtml** [thepurplebubble/site#53]
### What bug did you encounter?

The fonts in the form field clash with the fonts else where on the site

### What did you expect to happen?

The fonts would be a cohesive whole across the site

### Screenshots

![Image](https://github.com/thepurplebubble/site/assets/92754843/87602133-ad41-412e-88df-c7b40bb9ebbe)

### Additional information

This was reported by @graham on slack [https://hackclub.slack.com/archives/C068D2P46TH/p1716596507620519](https://hackclub.slack.com/archives/C068D2P46TH/p1716596507620519?thread_ts=1716596295.773529&cid=C068D2P46TH)

**Comment by akshatsinghania** [comment]
Please assign this to me, I will work on it!

**Comment by kcoderhtml** [comment]
I’ll assign you when I get home; can’t assign on mobile
